#spring:
#  cloud:
#    stream:
#      function:
#        definition: orderSupplier
#      bindings:
#        orderSupplier-out-0:
#          destination: order-event


spring:
  cloud:
    stream:
      function:
         definition: orderSupplier;paymentEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
